export const GIFTS = [
  { id: 1, name: "Star", image: "/gifts-reactions/star.png", price: 3 },
  { id: 2, name: "Happy Star", image: "/gifts-reactions/happy-start.png", price: 5 },
  { id: 3, name: "Sunflower", image: "/gifts-reactions/sunflower.png", price: 7 },
  { id: 4, name: "Joy Ride", image: "/gifts-reactions/joy-ride.png", price: 9 },
  { id: 5, name: "Rainbow", image: "/gifts-reactions/rainbow.png", price: 5 },
  { id: 6, name: "Target", image: "/gifts-reactions/target-locked.png", price: 11 },
  { id: 7, name: "Heart Box", image: "/gifts-reactions/hearts.png", price: 19 },
  { id: 8, name: "Sun", image: "/gifts-reactions/sunny.png", price: 5 },
  { id: 9, name: "Clap", image: "/gifts-reactions/applaud.png", price: 25 },
  { id: 10, name: "Bear Hi", image: "/gifts-reactions/hi.png", price: 35 },
  { id: 11, name: "Hamster", image: "/gifts-reactions/blush.png", price: 29 },
  { id: 12, name: "Bear", image: "/gifts-reactions/love-from-this-side.png", price: 45 },
  { id: 13, name: "Cheers", image: "/gifts-reactions/cheers.png", price: 49 },
  { id: 14, name: "Bunny", image: "/gifts-reactions/bunny.png", price: 39 },
  { id: 15, name: "Fire", image: "/gifts-reactions/fire.png", price: 15 },
  { id: 16, name: "Fireworks", image: "/gifts-reactions/sparkles.png", price: 45 },
  { id: 17, name: "Lips", image: "/gifts-reactions/kiss.png", price: 32 },
  { id: 18, name: "Rose", image: "/gifts-reactions/rose.png", price: 48 },
  { id: 19, name: "Aww", image: "/gifts-reactions/awww.png", price: 12 },
  { id: 20, name: "Laugh", image: "/gifts-reactions/laughing.png", price: 18 },
  { id: 21, name: "In Love", image: "/gifts-reactions/in-love.png", price: 22 },
  { id: 22, name: "Kiss", image: "/gifts-reactions/warm-kiss.png", price: 28 },
  { id: 23, name: "Heart", image: "/gifts-reactions/packed-heart.png", price: 8 },
  { id: 24, name: "Chocolaty", image: "/gifts-reactions/chocolaty.png", price: 34 },
  { id: 25, name: "Double Kisses", image: "/gifts-reactions/double-kisses.png", price: 42 },
  { id: 26, name: "Roses", image: "/gifts-reactions/rosees.png", price: 46 },
  { id: 27, name: "Flower Pot", image: "/gifts-reactions/flower-pot.png", price: 50 },
];
